name: Ruff Linter/Formatter

on:
  push:
    branches: ['main']

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Install ruff
        run: pip install ruff

      - name: Run the linter
        run: ruff check .

      - name: Run the format checker
        run: ruff format --check .

